disable button if card is owned in shop
ryanprice/Cryptoz.cards-Dapp pull request #43
Opened 2020-10-22 13:23 UTC by mchigit

Lots of reformatting. But the main changes are inside `ShopContent.getAllTypes`. 

Also removed watch on `totalCyptozTypes` because we only need to refetch all cards on mount. 

Also fixed help section

2020-10-22 17:55 UTC, jjjhill commented on src/components/ShopContent.vue
> +      console.log("SHOP currentEvent:", newValue);
remove log

2020-10-22 18:18 UTC, jjjhill commented on src/components/ShopContent.vue
> +        const indexes = Array.from(Array(totalCardTypes).keys());
es6 way: `const indexes = [...Array(totalCardTypes)].map((_,i) => i)`

2020-10-22 18:26 UTC, jjjhill commented on src/components/ShopContent.vue
> +          return cardData;
async/await might be extraneous here, promise.all expects an array of promises so you can just return this.getCard

2020-10-22 18:36 UTC, jjjhill commented on src/components/ShopContent.vue
> +        const storeCards = [...results.filter(result => result !== undefined)]
filter creates a new copy of the array already. dont need the extra shallow copy

2020-10-22 18:41 UTC, jjjhill commented on src/components/ShopContent.vue
> +            const enhancedCard = await this.isCardOwned(card);
you could call this right after `const cardData = await this.getCard(id + 1);` above to avoid the duplicate Promise.all

2020-10-22 18:47 UTC, jjjhill requested changes
minor es6 stuffs

2020-10-23 01:09 UTC, ryanprice requested changes
Getting an error when i try to Buy a card "must be in wei"

2020-10-23 01:53 UTC, mchigit commented
> Getting an error when i try to Buy a card "must be in wei"

I fixed this issue with `Math.round` for transaction value. But this doesn't solve the contract code problem when buying a card

2020-10-23 02:47 UTC, jjjhill approved these changes

2020-10-23 10:05 UTC, ryanprice approved these changes
help is working nice now, new disabled buy button looking good, lets merge this up

2020-10-23 23:47 UTC, merged